// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwJI-lKIgAXbjy80fQfN-yusTOvA4FfBs',
    appId: '1:728856518147:web:2c54fe3548e09830dbb836',
    messagingSenderId: '728856518147',
    projectId: 'careqr-new',
    authDomain: 'careqr-new.firebaseapp.com',
    storageBucket: 'careqr-new.firebasestorage.app',
    measurementId: 'G-7HEPGG2DNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX12jCeFYoCyPcxfB8-0l0SW0oHMpq8_8',
    appId: '1:728856518147:android:6292ff4fee6a6c9fdbb836',
    messagingSenderId: '728856518147',
    projectId: 'careqr-new',
    storageBucket: 'careqr-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5GGje6j0VhJPnfhI6lNFDj0g-8A8GKQ0',
    appId: '1:728856518147:ios:0dc527512f5cc427dbb836',
    messagingSenderId: '728856518147',
    projectId: 'careqr-new',
    storageBucket: 'careqr-new.firebasestorage.app',
    iosBundleId: 'com.example.careqrNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5GGje6j0VhJPnfhI6lNFDj0g-8A8GKQ0',
    appId: '1:728856518147:ios:0dc527512f5cc427dbb836',
    messagingSenderId: '728856518147',
    projectId: 'careqr-new',
    storageBucket: 'careqr-new.firebasestorage.app',
    iosBundleId: 'com.example.careqrNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwJI-lKIgAXbjy80fQfN-yusTOvA4FfBs',
    appId: '1:728856518147:web:53d344eff9da4707dbb836',
    messagingSenderId: '728856518147',
    projectId: 'careqr-new',
    authDomain: 'careqr-new.firebaseapp.com',
    storageBucket: 'careqr-new.firebasestorage.app',
    measurementId: 'G-V793L7D9CB',
  );
}
